### ISSUE TITLE
error while loading images from assets

### ISSUE THREAD

**Issue by LOG-TAG** [Pyozer/introduction_screen#10]
```
Widget _buildImage1() {
    return Align(
      child:  Image(image: AssetImage('assets/porsche_self_drive.png'),height: 175.0),
      alignment: Alignment.bottomCenter,
    );
  }
```

error:
![image](https://user-images.githubusercontent.com/1190344/67971599-0f325800-fc33-11e9-8788-fa768ed2e5a1.png)

where I'm missing pubspec details are perfectly fine!

**Comment by Pyozer** [comment]
Hi ;)

I think it's not an issue due to `Introduction_screen`, I tested and it's work perfectly fine for me, it's seem that you have not added your asset into the pubspec.yaml file.

You need to have this:
```yaml
flutter:
  assets:
    - assets/porsche_self_drive.png
```

Or you can also do this:
```yaml
flutter:
  assets:
    - assets/
```
